### ISSUE TITLE
DB: create Orders model

### ISSUE THREAD

**Issue by eseite47** [FSA-JEFS/Grace-Shopper#36]

**Comment by sw-yx** [comment]
Current order status
Items with quantity and subtotal
Link to the original product detail page
Date/time order was created
...so that I can remember exactly what I ordered and when

CART = "order we are currently working on"

**Comment by sw-yx** [comment]
ORDER STATUS:

Created, Processing, Cancelled, Completed

change the status of the order (Created -> Processing, Processing -> Cancelled || Completed)

**Comment by sw-yx** [comment]
Order

Orders must belong to a user OR guest session (authenticated vs unauthenticated)
Orders must contain line items that capture the price, current product ID and quantity
If a user completes an order, that order should keep the price of the item at the time when they checked out even if the price of the product later changes
